config/routes.rb
Rails.application.routes.draw do
  resources :nutritions do
    collection {post :import }
  end

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faqs'
  get 'welcome/pricing'
  get 'welcome/features'
  get 'welcome/login'

  get 'getdata' => 'pets#getdata'
   resources :pets
   resources :nutritionfacts
   resources :foods
   resources :recipes
   resources :idealdogweights
   resources :idealcatweights

   root 'welcome#index'

    

end

app/models/food.rb
class Food < ActiveRecord::Base
	has_one :nutritionfact, :dependent => :destroy
end

app/models/idealcatweight.rb
class Idealcatweight < ActiveRecord::Base
end

app/models/idealdogweight.rb
class Idealdogweight < ActiveRecord::Base
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Nutrition.create! row.to_hash
		end
	end
end

app/models/nutritionfact.rb
class Nutritionfact < ActiveRecord::Base
	belongs_to :food
end

app/models/pet.rb
class Pet < ActiveRecord::Base

    
    validates :gender, presence:true
    validates :body_weight, :numericality=>true, :presence=>true
    validates :pet_type, presence:true
    validates :breed, presence:true
    validates :body_condition_score, presence:true
    validates :age, :numericality=>true, :presence=>true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end

	def show
		@food = Food.find(params[:id])
	end

	def new
		@food = Food.new
	end


	def create
		@food = Food.new(food_params)
		if @food.save
			redirect_to @food
		else
			render 'new'
		end
	end

	private
		def food_params
			params.require(:food).permit(:name, :description, :referencePrice, :ediblePercentage, :cookMethod, :foodCategory)
		end
end

app/controllers/idealcatweights_controller.rb
class IdealcatweightsController < ApplicationController
end

app/controllers/idealdogweights_controller.rb
class IdealdogweightsController < ApplicationController
end

app/controllers/nutritionfacts_controller.rb
class NutritionfactsController < ApplicationController
	def index
		@nutritionfacts = Nutritionfact.all
	end

	def show
		@nutritionfact = Nutritionfact.find(params[:id])
	end

	def new
		@nutritionfact = Nutritionfact.new
	end


	def create
		@nutritionfact = Nutritionfact.new(nutritionfact_params)
		if @nutritionfact.save
			redirect_to @nutritionfact
		else
			render 'new'
		end
	end

	private
		def nutritionfact_params
			params.require(:nutritionfact).permit(
		       :category,
		       :foodname,
		       :weight,
		       :edible,
		       :energy,
		       :protein,
		       :fat,
		       :cho,
		       :dietaryfiber,
		       :ash,
		       :cholesterol,
		       :vitaminA,
		       :retinol,
		       :vitaminE,
		       :vitaminB1,
		       :vitaminB2,
		       :vitaminB3,
		       :calcium,
		       :phoshorous,
		       :potassium,
		       :sodium,
		       :magnesium,
		       :iron,
		       :zinc,
		       :selenium,
		       :copper,
		       :manganese
			)
		end
end

app/controllers/nutritions_controller.rb
class NutritionsController < ApplicationController
  before_action :set_nutrition, only: [:show, :edit, :update, :destroy]

  # GET /nutritions
  # GET /nutritions.json
  def index
    @nutritions = Nutrition.all
  end

  # GET /nutritions/1
  # GET /nutritions/1.json
  def show
  end

  # GET /nutritions/new
  def new
    @nutrition = Nutrition.new
  end

  # GET /nutritions/1/edit
  def edit
  end

  # POST /nutritions
  # POST /nutritions.json
  def create
    @nutrition = Nutrition.new(nutrition_params)

    respond_to do |format|
      if @nutrition.save
        format.html { redirect_to @nutrition, notice: 'Nutrition was successfully created.' }
        format.json { render :show, status: :created, location: @nutrition }
      else
        format.html { render :new }
        format.json { render json: @nutrition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nutritions/1
  # PATCH/PUT /nutritions/1.json
  def update
    respond_to do |format|
      if @nutrition.update(nutrition_params)
        format.html { redirect_to @nutrition, notice: 'Nutrition was successfully updated.' }
        format.json { render :show, status: :ok, location: @nutrition }
      else
        format.html { render :edit }
        format.json { render json: @nutrition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutritions/1
  # DELETE /nutritions/1.json
  def destroy
    @nutrition.destroy
    respond_to do |format|
      format.html { redirect_to nutritions_url, notice: 'Nutrition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Nutrition.import(params[:file])
    redirect_to nutritions_path, notice: "nutritions added successfully"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nutrition
      @nutrition = Nutrition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nutrition_params
      params.require(:nutrition).permit(:category, :foodname, :weight, :edible, :energy, :protein, :fat, :cho, :dietaryfiber, :ash, :cholesterol, :vitaminA, :retinol, :vitaminE, :vitaminB1, :vitaminB2, :vitaminB3, :calcium, :phoshorous, :potassium, :sodium, :magnesium, :iron, :zinc, :selenium, :copper, :manganese, :food_id)
    end
end

app/controllers/pets_controller.rb
require 'csv'

class PetsController < ApplicationController
    def index
	
    @pets = Pet.all
    end
    
	def new
        @pet=Pet.new
	end

  def create
   
  	@pet = Pet.new(pet_params)

  	if @pet.save
        redirect_to @pet
   	else
      	render 'new'
    end
	end

  def edit
  @pet = Pet.find(params[:id])
  end

  def show
        @pet=Pet.find(params[:id])
  end

  def getdata

    # this contains what has been selected in the first select box

    Rails.logger.debug("Params: #{params[:pet][:pet_type]}")
    Rails.logger.debug('test3')
    # we get the data for selectbox 2
    if params[:pet][:pet_type] == "Dog"
    @data_for_select2 = Idealdogweight.all
    end
    if params[:pet][:pet_type] == "Cat"
    @data_for_select2 = Idealcatweight.all
    end
    Rails.logger.debug("Params: #{@data_select2.inspect}")

    
    
    if params[:pet][:pet_type] != ""

    # render an array in JSON containing arrays like:
    #[[:id1, :name1], [:id2, :name2]]
    render :json => @data_for_select2.map{|c| [c.english_name, c.english_name]}
    else

    render :json => [['',''],['','']]
    end
  end

def update
  @pet = Pet.find(params[:id])
 
  if @pet.update(pet_params)
    redirect_to @pet
  else
    render 'edit'
  end
end


private
  def pet_params
  	  
      params.require(:pet).permit(:name, :gender, :age, :pet_type, :body_condition_score, :body_weight, :breed, :activity)
	
  end

     
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faqs
  end

  def pricing
  end

  def features
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/idealcatweights_helper.rb
module IdealcatweightsHelper
end

app/helpers/idealdogweights_helper.rb
module IdealdogweightsHelper
end

app/helpers/nutritionfacts_helper.rb
module NutritionfactsHelper
end

app/helpers/nutritions_helper.rb
module NutritionsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/index.html.erb
<div class='container-fluid text-center'>
  <h1>Food lists</h1>
      <table >
        <tr class=>
          <th>Food Category</th>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.foodCategory %></td>
            <td><%= food.name %></td>
            <td><%= link_to 'See Details', food_path(food) %></td>
            <td><%= link_to 'See NutritionFacts',nutritionfacts_path%></td>
            <td><%= link_to 'Add into Recipe', recipes_path%></td>
         </tr>
       <% end %></div>
     </table>
</div> 
<div align="center" id="ctn">
<a href="http://localhost:3000/foods/new" class="btn2">Add new food</a>
<a href="http://localhost:3000/welcome/index" class="btn2">Back</a></div>

app/views/foods/new.html.erb
<div class='container-fluid'><h1>New Food</h1>
<div style="width:60px" class='col-md-1 col-md-offset-4' id="ctn2">
  <%= form_for :food, url: foods_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
   
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.label :referencePrice %><br>
      <%= f.text_area :referencePrice %>
    </p>
    
    <p>
      <%= f.label :ediblePercentage %><br>
      <%= f.text_area :ediblePercentage %>
    </p>
   
    <p>
      <%= f.label :cookMethod %><br>
      <%= f.text_area :cookMethod %>
    </p>

    <p>
      <%= f.label :foodCategory %><br>
      <%= f.text_area :foodCategory %>
    </p>

    <p>
      <%= f.submit nil, :class => 'btn2' %>
    </p>
  <% end %>


<a href="http://localhost:3000/foods" class="btn2">Back</a>
</div> 
</div>

app/views/foods/show.html.erb
<div class='container-fluid'>
<h1>Food Details</h2>
<div style="width:400px" class='col-md-2 col-md-offset-4' id="ctn4">
<p>
  <strong>name:</strong>
  <%= @food.name %>
</p>
 
<p>
  <strong>description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>referencePrice:</strong>
  <%= @food.referencePrice %>
</p>

<p>
  <strong>ediblePercentage:</strong>
  <%= @food.ediblePercentage %>
</p>
<p>
  <strong>cookMethod:</strong>
  <%= @food.cookMethod %>
</p>

<p>
  <strong>foodCategory:</strong>
  <%= @food.foodCategory %>
</p>
<div id="ctn0"><p>  </p></div>
<div class="col-md-12" align="center"><a href="http://localhost:3000/foods" class="btn2">Back</a></div></div>

app/views/nutritionfacts/index.html.erb
<h1>nutritionFact list here:</h1>
<%= link_to 'Add nutritionfacts', new_nutritionfact_path %>
<table>
  <tr>

      <th>nutritionfact.foodname</th>
      <th>nutritionfact.weight</th>
      <th>nutritionfact.edible</th>
      <th>nutritionfact.energy</th>
      <th>nutritionfact.protein</th>
      <th>nutritionfact.fat</th>
      <th>nutritionfact.cho</th>
      <th>nutritionfact.dietaryfiber</th>
      <th>nutritionfact.ash</th>

    <th colspan="1"></th>
  </tr>
 
  <% @nutritionfacts.each do |nutritionfact| %>
    <tr>

      <td><%= nutritionfact.foodname %></td>
      <td><%= nutritionfact.weight %></td>
      <td><%= nutritionfact.edible %></td>
      <td><%= nutritionfact.energy %></td>
      <td><%= nutritionfact.protein %></td>
      <td><%= nutritionfact.fat %></td>
      <td><%= nutritionfact.cho %></td>
      <td><%= nutritionfact.dietaryfiber %></td>
      <td><%= nutritionfact.ash %></td>

      <td><%= link_to 'Add into Recipe', recipes_path%></td>
    </tr>
  <% end %>
</table>

app/views/nutritionfacts/new.html.erb
<h1>New Nutritionfacts</h1>
<%= form_for :nutritionfact, url: nutritionfacts_path do |f| %>
  <p>
    <%= f.label :foodname %><br>
    <%= f.text_field :foodname %>
  </p>
  
  <p>
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </p>

  <p>
    <%= f.label :edible %><br>
    <%= f.text_field :edible %>
  </p>
  
  <p>
    <%= f.label :energy %><br>
    <%= f.text_field :energy %>
  </p>
 
  <p>
    <%= f.label :protein %><br>
    <%= f.text_field :protein %>
  </p>

  <p>
    <%= f.label :fat %><br>
    <%= f.text_field :fat %>
  </p>

  <p>
    <%= f.label :cho %><br>
    <%= f.text_field :cho %>
  </p>

  <p>
    <%= f.label :dietaryfiber %><br>
    <%= f.text_field :dietaryfiber %>
  </p>

  <p>
    <%= f.label :ash %><br>
    <%= f.text_field :ash %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', nutritionfacts_path %>

app/views/nutritionfacts/show.html.erb
<p>
  <strong>foodname:</strong>
  <%= @nutritionfact.foodname %>
</p>

<p>
  <strong>weight:</strong>
  <%= @nutritionfact.weight %>
</p>

<p>
  <strong>edible:</strong>
  <%= @nutritionfact.edible %>
</p>


<p>
  <strong>energy:</strong>
  <%= @nutritionfact.energy %>
</p>
 
<p>
  <strong>protein:</strong>
  <%= @nutritionfact.protein %>
</p>

<p>
  <strong>fat:</strong>
  <%= @nutritionfact.fat %>
</p>

<p>
  <strong>cho:</strong>
  <%= @nutritionfact.cho %>
</p>

<p>
  <strong>dietaryfiber:</strong>
  <%= @nutritionfact.dietaryFiber %>
</p>

<p>
  <strong>ash:</strong>
  <%= @nutritionfact.ash %>
</p>

<%= link_to 'Back', nutritionfacts_path %>

app/views/nutritions/edit.html.erb
<h1>Editing Nutrition</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutrition %> |
<%= link_to 'Back', nutritions_path %>

app/views/nutritions/index.html.erb
<div class='container-fluid'><p id="notice"><%= notice %></p>

<h1>Listing Nutritions</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Category</th>
        <th>Foodname</th>
        <th>Weight</th>
        <th>Edible</th>
        <th>Energy</th>
        <th>Protein</th>
        <th>Fat</th>
        <th>Cho</th>
        <th>Dietaryfiber</th>
        <th>Ash</th>
        <th>Cholesterol</th>
        <th>Vitamina</th>
        <th>Retinol</th>
        <th>Vitamine</th>
        <th>Vitaminb1</th>
        <th>Vitaminb2</th>
        <th>Vitaminb3</th>
        <th>Calcium</th>
        <th>Phosphorous</th>
        <th>Potassium</th>
        <th>Sodium</th>
        <th>Magnesium</th>
        <th>Iron</th>
        <th>Zinc</th>
        <th>Selenium</th>
        <th>Copper</th>
        <th>Manganese</th>
        <th>Food</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
        <% @nutritions.each do |nutrition| %>
          <tr>
            <td><%= nutrition.category %></td>
            <td><%= nutrition.foodname %></td>
            <td><%= nutrition.weight %></td>
            <td><%= nutrition.edible %></td>
            <td><%= nutrition.energy %></td>
            <td><%= nutrition.protein %></td>
            <td><%= nutrition.fat %></td>
            <td><%= nutrition.cho %></td>
            <td><%= nutrition.dietaryfiber %></td>
            <td><%= nutrition.ash %></td>
            <td><%= nutrition.cholesterol %></td>
            <td><%= nutrition.vitaminA %></td>
            <td><%= nutrition.retinol %></td>
            <td><%= nutrition.vitaminE %></td>
            <td><%= nutrition.vitaminB1 %></td>
            <td><%= nutrition.vitaminB2 %></td>
            <td><%= nutrition.vitaminB3 %></td>
            <td><%= nutrition.calcium %></td>
            <td><%= nutrition.phosphorous %></td>
            <td><%= nutrition.potassium %></td>
            <td><%= nutrition.sodium %></td>
            <td><%= nutrition.magnesium %></td>
            <td><%= nutrition.iron %></td>
            <td><%= nutrition.zinc %></td>
            <td><%= nutrition.selenium %></td>
            <td><%= nutrition.copper %></td>
            <td><%= nutrition.manganese %></td>
            <td><%= nutrition.food_id %></td>
            <td><%= link_to 'Show', nutrition %></td>
            <td><%= link_to 'Edit', edit_nutrition_path(nutrition) %></td>
            <td><%= link_to 'Destroy', nutrition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<h3>Import Nutritions</h3>
<%= form_tag import_nutritions_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload nutritions" %>
<% end %>

<%= link_to 'New Nutrition', new_nutrition_path %>
</div>

app/views/nutritions/new.html.erb
<h1>New Nutrition</h1>

<%= render 'form' %>

<%= link_to 'Back', nutritions_path %>

app/views/nutritions/show.html.erb
<div class="container-fluid"><p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @nutrition.category %>
</p>

<p>
  <strong>Foodname:</strong>
  <%= @nutrition.foodname %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @nutrition.weight %>
</p>

<p>
  <strong>Edible:</strong>
  <%= @nutrition.edible %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @nutrition.energy %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @nutrition.protein %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @nutrition.fat %>
</p>

<p>
  <strong>Cho:</strong>
  <%= @nutrition.cho %>
</p>

<p>
  <strong>Dietaryfiber:</strong>
  <%= @nutrition.dietaryfiber %>
</p>

<p>
  <strong>Ash:</strong>
  <%= @nutrition.ash %>
</p>

<p>
  <strong>Cholesterol:</strong>
  <%= @nutrition.cholesterol %>
</p>

<p>
  <strong>Vitamina:</strong>
  <%= @nutrition.vitaminA %>
</p>

<p>
  <strong>Retinol:</strong>
  <%= @nutrition.retinol %>
</p>

<p>
  <strong>Vitamine:</strong>
  <%= @nutrition.vitaminE %>
</p>

<p>
  <strong>Vitaminb1:</strong>
  <%= @nutrition.vitaminB1 %>
</p>

<p>
  <strong>Vitaminb2:</strong>
  <%= @nutrition.vitaminB2 %>
</p>

<p>
  <strong>Vitaminb3:</strong>
  <%= @nutrition.vitaminB3 %>
</p>

<p>
  <strong>Calcium:</strong>
  <%= @nutrition.calcium %>
</p>

<p>
  <strong>Phoshorous:</strong>
  <%= @nutrition.phoshorous %>
</p>

<p>
  <strong>Potassium:</strong>
  <%= @nutrition.potassium %>
</p>

<p>
  <strong>Sodium:</strong>
  <%= @nutrition.sodium %>
</p>

<p>
  <strong>Magnesium:</strong>
  <%= @nutrition.magnesium %>
</p>

<p>
  <strong>Iron:</strong>
  <%= @nutrition.iron %>
</p>

<p>
  <strong>Zinc:</strong>
  <%= @nutrition.zinc %>
</p>

<p>
  <strong>Selenium:</strong>
  <%= @nutrition.selenium %>
</p>

<p>
  <strong>Copper:</strong>
  <%= @nutrition.copper %>
</p>

<p>
  <strong>Manganese:</strong>
  <%= @nutrition.manganese %>
</p>

<p>
  <strong>Food:</strong>
  <%= @nutrition.food_id %>
</p>

<%= link_to 'Edit', edit_nutrition_path(@nutrition) %> |
<%= link_to 'Back', nutritions_path %>
</div>

app/views/pets/edit.html.erb
<div class='container-fluid'><h1>Editing pet</h1>
 
<%= form_for :pet, url: pet_path(@pet), method: :patch do |f| %>
 
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style="width:60px" class='col-md-1 col-md-offset-4' id="ctn2">
  <p>
    <%= f.label :gender %><br>
    <select name="gender">
    <option value="Male">Male</option>
    <option value="Female">Female</option>
    
</select>
  </p>

  <p>
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </p>

<p>
   <%= f.label "Pet Type" %><br>
<%= 
  f.select :pet_type,options_for_select([["Cat", "Cat"], ['Dog',"Dog"]]),{:include_blank=>true}, :id=>"first_select", 
      :'data-remote' => 'true', # important for UJS
      :'data-url' => url_for(:controller => 'pets', :action => 'getdata'), # we get the data from here!
      :'data-type' => 'json' # tell jQuery to parse the response as JSON!
%>
</p>
<%= f.label :Breed %><br>
<%= 
  f.select :breed,"<option>Please select something from first select!</option>",{},:id=>"second_select"
%> 

  <p>
    <%= f.label :body_condition_score %><br>
    <%= f.text_field :body_condition_score %>
  </p>

  <p>
    <%= f.label :weight %><br>
    <%= f.text_field :body_weight %>
  </p>


<p>
    <%= f.label :weight %><br>
    <%= f.text_field :body_weight %>
  </p>

  <p>
    <%= f.label :activity_level %><br>
    <select name="activity_level">
    <option value="indoor">Indoor</option>
    <option value="outdoor">Outdoor</option>
    </select>
  </p>

  <p>
    <%= f.submit nil, :class => 'btn2'  %>
  </p>
 
<% end %>
 
<a href="http://localhost:3000/pets" class="btn2">Back</a>
</div>
</div>

app/views/pets/index.html.erb
<div class = 'container-fluid'><h1>Check All You Pets Here!</h1>
 
<div class='text-center'><table>
  <tr>
    <th>Name&nbsp</th>
    <th>Age&nbsp</th> 
    <th>Gender&nbsp</th>
    <th>Pet Type&nbsp</th>
    <th>Body Condition Score&nbsp</th>
    <th>Weight&nbsp</th>
    <th>Activity Level&nbsp</th>
    <th colspan="2"></th>
  </tr>
 
  <% @pets.each do |pet| %>
    <tr>
      <td><%= pet.name %></td>
      <td><%= pet.age %></td>
      <td><%= pet.gender %></td>
      <td><%= pet.pet_type %></td>
      <td><%= pet.body_condition_score %></td>
      <td><%= pet.body_weight %></td>
      <td><%= pet.activity %></td>

    </tr>

  <% end %>
</table></div>
<div align="center" id="ctn">
<a href="http://localhost:3000/foods" class="btn2">Select food for pets</a>
<a href="http://localhost:3000/pets/new" class="btn2">Add new pets</a>
</div>
<div align="center"><a href="http://localhost:3000/welcome/index" class="btn2">Back to welcome page</a></div>
</div>

app/views/pets/new.html.erb
<div class='container-fluid col-md-12'><h1>Adding a Pet</h1>

  
    <%= form_for :pet, url: pets_path(@pet) do |f| %>
      <% if @pet.errors.any? %>
        <div id="error_explanation" align= "center">
          <h2>
            <%= pluralize(@pet.errors.count, "error") %> prohibited
            this pet from being saved:
          </h2>
          <ul>
            <% @pet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div style="width:60px" class='col-md-1 col-md-offset-4' id="ctn2">
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
      	<%= f.label "Gender" %><br>
      	<%= f.select(:gender,options_for_select([['Male',"Male"],	 
              ['Female',"Female"]])) %>
        </p>

        <p>
          <%= f.label "Age (in years)" %><br>
          <%= f.text_field :age %>
        </p>
        <p>
         <%= f.label "Pet Type" %><br>
      <%= 
        f.select :pet_type,options_for_select([["Cat", "Cat"], ['Dog',"Dog"]]),{:include_blank=>true}, :id=>"first_select", 
            :'data-remote' => 'true', # important for UJS
            :'data-url' => url_for(:controller => 'pets', :action => 'getdata'), # we get the data from here!
            :'data-type' => 'json' # tell jQuery to parse the response as JSON!
        %></p>
   
    </p><%= f.label :Breed %><br>
    <%= f.select(:breed,options_for_select([['Slim/Normal',"Normal"],             ['Fat',"Fat"]])) %></p>

      <p>
        <%= f.label :body_condition_score %><br>
        <%= f.select(:body_condition_score,options_for_select([['Slim/Normal',"Normal"],   	   	  	['Fat',"Fat"]])) %>
      </p>

      <p>
        <%= f.label "weight in Kg" %><br>
        <%= f.text_field :body_weight %>
      </p>

      <p>
        <%= f.label :activity_level %><br>
       <%= f.select(:activity,options_for_select([['Active',"Active"],   	   	  	['Inactive',"Inactive"]])) %>
      </p>

     

     
     




      <!--pet type, gender, date of birth (age), body condition score, body weight, activity level (indoor / backyard), sterilization time, vaccination history in vivo anthelmintic time vitro flea flooding time, diet (optional homemade, canned food, cat food, snacks)-->
      
    <p><%= f.submit nil, :class => 'btn2' %></p>
    <% end %>
     <a href="http://localhost:3000/pets" class="btn2">Back</a></div>
</div>

app/views/pets/show.html.erb
<h1>Pet info</h1>
<div style="width:600px" class='col-md-2 col-md-offset-3' id="ctn3"><p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @pet.gender %>
</p>
 
<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Pet Type:</strong>
  <%= @pet.pet_type %>
</p>

<p>
  <strong>Body Condition Score:</strong>
  <%= @pet.body_condition_score %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.body_weight %>
</p>

<p>
  <strong>Activity Level:</strong>
  <%= @pet.activity%>
</p>

<div id="ctn0"><p>  </p></div>
<a href="http://localhost:3000/pets" class="btn2">Edit</a>
<a href="http://localhost:3000/pets" class="btn2">Back</a>
<%= link_to 'Edit', edit_pet_path(@pet) %> 
<div id="ctn0"><p>  </p></div>
<a href="http://localhost:3000/pets/new" class="btn2">Add a new pet</a>
<div id="ctn0"><p>  </p></div>
<a href="http://localhost:3000/foods" class="btn2">Select food</a>

</div>